### ISSUE TITLE
Requesting a few more utility methods

### ISSUE THREAD

**Issue by mit-mit** [lrhn/unicode#1]
`dropFirst(int count): GraphemeClusters`: Returns the range containing all but the count initial grapheme clusters
`dropLast(int count): GraphemeClusters`: Returns the range containing all but the count last grapheme clusters
`append(String): GraphemeClusters`: Returns this string with String appended.
`insert(GraphemeCluster char, int position)`: Returns this string with char inserted at the specified position.
`lowercased`: Returns a lowercase version of this string.
`uppercased`: Returns a uppercase version of this string.

**Comment by mit-mit** [comment]
cc @lrhn

**Comment by lrhn** [comment]
Added:
* `skipLast(count)`, `takeLast(count)`, `skipLastWhile(test)`, `takeLastWhile(test)` (and made `skip`/`take`/`skipWhile`/`takeWhile`/`where`  be eager and return a `GraphemeClusters`.
* `operator+` (just concatenates strings and returns the `GraphemeClusters` of that, differs from `Iterable.followedBy` which doesn't combine grahemes clusters at the edge).
* `toUpperCase()`, `toLowerCase()`
* `insertAt(int, GrpahemeClusters)` and `replaceRange(int, int, GraphemeClusters)` which just pass the operation to the underlying string and rewraps the result.
* `operator==` and `hashCode`.
